---
- name: psql install and start services
  hosts: all
  become: true

  tasks:
  - name: install Postgresql 
    apt:
      name: postgresql
      state: present

  - name: Ensure state
    service:
      name: postgresql
      state: started
      enabled: true
 
  - name: add line to the postgresql.conf
    lineinfile:
      path: /etc/postgresql/12/main/postgresql.conf
      state: present
      line: "{{ item }}"
    with_items:
    - "log_statement = 'all'"
    - "log_directory = 'pg_log'"
    - "log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'"
    - "logging_collector = 'on'"
    - "log_min_error_statement = 'error'"
    - "log_destination = 'stderr'"
   
  - name: Restart Postgresql service
    ansible.builtin.service:
      name: postgresql
      state: restarted
      
